// Bank.js
export const ADD_BANK = "ADD_BANK";
export const REMOVE_BANK = "REMOVE_BANK";
export const DEPOSIT_MONEY_TO_BANK_ACCOUNT = "DEPOSIT_MONEY_TO_BANK_ACCOUNT";
export const WITHDRAW_MONEY_FROM_BANK_ACCOUNT =
  "WITHDRAW_MONEY_FROM_BANK_ACCOUNT";
// Expenses.js
export const ADD_EXPENSE = "ADD_EXPENSE";
export const REMOVE_EXPENSE = "REMOVE_EXPENSE";
export const EDIT_EXPENSE = "EDIT_EXPENSE";
export const SET_EXPENSES = "SET_EXPENSES";

// Others-income.js
export const ADD_INCOME = "ADD_INCOME";
export const REMOVE_INCOME = "REMOVE_INCOME";
export const EDIT_INCOME = "EDIT_INCOME";
export const SET_INCOMES = "SET_INCOMES";

// Sells.js
export const ADD_A_SELL_ITEM = "ADD_A_SELL_ITEM";
export const REMOVE_A_SELL_ITEM = "REMOVE_A_SELL_ITEM";
export const MAKE_EMPTY_A_SELL_ITEMS = "MAKE_EMPTY_A_SELL_ITEMS";
export const REMOVE_ALL_SELL_ITEMS = "REMOVE_ALL_SELL_ITEMS";
export const ADD_A_CUSTOMER = "ADD_A_CUSTOMER";
export const REMOVE_CUSTOMERS = "REMOVE_CUSTOMERS";
export const ADD_SELL_UNDER_CUSTOMER_HISTORY =
  "ADD_SELL_UNDER_CUSTOMER_HISTORY";
export const ADD_A_PREV_DUE = "ADD_A_PREV_DUE";
export const INCREMENT_MEMO_NUMBER = "INCREMENT_MEMO_NUMBER";
export const START_SET_MEMO_NUMBER = "START_SET_MEMO_NUMBER";
export const DELETE_SELL_UNDER_CUSTOMER_HISTORY =
  "DELETE_SELL_UNDER_CUSTOMER_HISTORY";
export const SET_ADD_SELL_UNDER_CUSTOMER_HISTORY =
  "SET_ADD_SELL_UNDER_CUSTOMER_HISTORY";
export const DELETE_ALL_HISTORY_OF_THIS_NUMBER =
  "DELETE_ALL_HISTORY_OF_THIS_NUMBER";
export const ADD_A_TABLE = "ADD_A_TABLE";
export const REMOVE_ALL_TABLE = "REMOVE_ALL_TABLE";
// Stock.js
export const SET_STOCK = "SET_STOCK";
export const ADD_ITEM_TO_STOCK = "ADD_ITEM_TO_STOCK";
export const REMOVE_ITEM_FROM_STOCK = "REMOVE_ITEM_FROM_STOCK";
export const UPDATE_STOCK_ITEM = "UPDATE_STOCK_ITEM";
// Due.js
export const SET_DUE_TEXT_FILTER = "SET_DUE_TEXT_FILTER";
export const SET_DUE = "SET_DUE";
export const REMOVE_A_PREV_DUE = "REMOVE_A_PREV_DUE";
export const UPDATE_A_PREV_DUE = "UPDATE_A_PREV_DUE";
// Ready-Cash.js
export const ADD_AN_ENTRY_TO_READY_CASH = "ADD_AN_ENTRY_TO_READY_CASH";
export const REMOVE_AN_ENTRY_FROM_READY_CASH =
  "REMOVE_AN_ENTRY_FROM_READY_CASH";
export const SET_READY_CASH = "SET_READY_CASH";
export const RESET_READY_CASH = "RESET_READY_CASH";

export const UPDATE_READY_CASH_AMOUNT = "UPDATE_READY_CASH_AMOUNT";
export const SET_READY_CASH_AMOUNT = "SET_READY_CASH_AMOUNT";
export const OVERRIDE_READY_CASH_AMOUNT = "OVERRIDE_READY_CASH_AMOUNT";

// Store Infomation
export const UPDATE_STORE_INFO = "UPDATE_STORE_INFO";
export const SET_STORE_INFO = "SET_STORE_INFO";

// auth.js

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

// Advance.js
export const ADD_ADVANCE = "ADD_ADVANCE";
export const REMOVE_ADVANCE = "REMOVE_ADVANCE";
export const EDIT_ADVANCE = "EDIT_ADVANCE";
export const SET_ADVANCES = "SET_ADVANCES";
